### ISSUE TITLE
Corrupted source for bzip2/1.0.6@conan/stable

### ISSUE THREAD

**Issue by acgetchell** [conan-community/conan-bzip2#13]
From https://travis-ci.org/acgetchell/causal-sets-explorer/jobs/413613626:

bzip2/1.0.6@conan/stable: Building your package in /Users/travis/.conan/data/bzip2/1.0.6/conan/stable/build/c150e1f5b5a8686f3d87440f6aef5dd118e08085
bzip2/1.0.6@conan/stable: Configuring sources in /Users/travis/.conan/data/bzip2/1.0.6/conan/stable/source
[==================================================] 272B/195B        
bzip2/1.0.6@conan/stable: WARN: Trying to remove corrupted source folder
bzip2/1.0.6@conan/stable: WARN: This can take a while for big packages
ERROR: bzip2/1.0.6@conan/stable: Error in source() method, line 34
	tools.check_md5(zip_name, "00b516f4704d4a7cb50a1d97e6e8e15b")
	ConanException: md5 signature failed for 'bzip2-1.0.6.tar.gz' file. 
 Provided signature: 00b516f4704d4a7cb50a1d97e6e8e15b  
 Computed signature: bf0e786f0f6b34030568fddc063d658d

**Comment by acgetchell** [comment]
This problem doesn't happen if the package isn't built, e.g. 

https://travis-ci.org/acgetchell/causal-sets-explorer/jobs/413613627

**Comment by aledeganopix4d** [comment]
It appears that the domain www.bzip.org has expired.

**Comment by danimtb** [comment]
There is a reddit discussion on where to download the sources now the domain is not working: https://www.reddit.com/r/linux/comments/95uyo9/bziporg_seems_to_be_gone_any_alternatives/

Someone got the sources of 1.0.6 version and put them in here: https://gitlab.com/bzip/bzip2 but I am not sure if this is a good source to rely on...

**Comment by firewave** [comment]
There is a discussion linked in the reddit thread - https://lwn.net/Articles/762264/

The article of interest appears to be https://lwn.net/Articles/762340/

**Comment by acgetchell** [comment]
Any updates on this? Bzip2 is required by boost, which is required by all of the scientific libraries I use.

**Comment by acgetchell** [comment]
Ah, there are now updates for xenial/g++-8 and xenial/clang-6.

**Comment by lasote** [comment]
Hi, I fixed the sources for bzip2 in the package. I uploaded the original tgz to bintray https://bintray.com/conan/Sources/download_file?file_path=bzip2-1.0.6.tar.gz
Now you should be able to generate the GCC packages if needed.

**Comment by VladasZ** [comment]
I have the same issue building freetype/2.9.0@bincrafters/stable. Computed signature is different each time i run conan. Conan version 1.6.1.
```
['conan', 'install', '..', '--build=missing', '-scompiler=gcc', '-scompiler.version=8.1', '-scompiler.libcxx=libstdc++']
bzip2/1.0.6@conan/stable: WARN: Package is corrupted, removing folder: C:\Users\u.zakreuskis\.conan\data\bzip2\1.0.6\conan\stable\package\3eb7158014aa4348d564a116a6781ce49065179f
PROJECT: Installing C:\Users\u.zakreuskis\dev\projects\TestEngine\conanfile.txt
Requirements
    bzip2/1.0.6@conan/stable from 'conan-center' - Cache
    freetype/2.9.0@bincrafters/stable from 'conan-center' - Cache
    libpng/1.6.34@bincrafters/stable from 'conan-center' - Cache
    zlib/1.2.11@conan/stable from 'conan-center' - Cache
Packages
    bzip2/1.0.6@conan/stable:3eb7158014aa4348d564a116a6781ce49065179f - Build
    freetype/2.9.0@bincrafters/stable:37aa76607cffc70d5eae4d69d7e45739305dded0 - Build
    libpng/1.6.34@bincrafters/stable:814ebfa5186d998e34f569d194f81dba5a088811 - Build
    zlib/1.2.11@conan/stable:eb34f13b437ddfd63abb1f884c4b8886c48b74cd - Build

bzip2/1.0.6@conan/stable: Building your package in C:\Users\u.zakreuskis\.conan\data\bzip2\1.0.6\conan\stable\build\3eb7158014aa4348d564a116a6781ce49065179f
bzip2/1.0.6@conan/stable: WARN: Trying to remove corrupted source folder
bzip2/1.0.6@conan/stable: WARN: This can take a while for big packages
bzip2/1.0.6@conan/stable: Configuring sources in C:\Users\u.zakreuskis\.conan\data\bzip2\1.0.6\conan\stable\source

bzip2/1.0.6@conan/stable: WARN: Trying to remove corrupted source folder
bzip2/1.0.6@conan/stable: WARN: This can take a while for big packages
ERROR: bzip2/1.0.6@conan/stable: Error in source() method, line 34
        tools.check_md5(zip_name, "00b516f4704d4a7cb50a1d97e6e8e15b")
        ConanException: md5 signature failed for 'bzip2-1.0.6.tar.gz' file.
 Provided signature: 00b516f4704d4a7cb50a1d97e6e8e15b
 Computed signature: dc36952c6ad78e1ab36d8158b52317ec
```

**Comment by VladasZ** [comment]
@danimtb yes. It helped. Thank you.
