### ISSUE TITLE
conan search is broken, but only of stable

### ISSUE THREAD

**Issue by spavlovskyi** [conan-community/conan-bzip2#14]
`conan search bzip2 -r conan-center` returns ```bzip2/1.0.6@conan/stable
bzip2/1.0.6@conan/testing```
`conan search bzip2/1.0.6@conan/stable -r conan-center` returns ```ERROR: Unable to retrieve resource.. [Remote: conan-center]```
`conan get bzip2/1.0.6@conan/stable -r conan-center` works
installing as requirement works
`conan search bzip2/1.0.6@conan/testing -r conan-center` works
tested with clean cache and from different host

**Comment by lasote** [comment]
Confirmed. It is an issue with the Bintray service. Will report ASAP.

**Comment by SSE4** [comment]
This issue was moved to conan-community/community#66
