### ISSUE TITLE
bzip2 fails on macOS 10.14

### ISSUE THREAD

**Issue by acgetchell** [conan-community/conan-bzip2#20]
Description of Problem, Request, or Question

bzip2/1.0.6@conan/stable fails to build on macOS 10.14:

https://ci.appveyor.com/project/acgetchell/cdt-plusplus/build/job/gni54v03r5vs68a5#L5610

Package Details (Include if Applicable)

Package Name/Version: bzip2/1.0.6@conan/stable
Operating System: macOS 10.14
Compiler+version: apple-clang 10.0
Steps to reproduce (Include if Applicable)

Run build script locally:

https://github.com/acgetchell/CDT-plusplus/blob/develop/build.sh

Results:

┌─[adam][hapkido][±][feature/refactor-simplicial-manifold ?:1 ✗][~/CDT-plusplus]
└─▪ ./build.sh 
Downloading conaninfo.txt
[==================================================] 150B/150B        
Downloading conaninfo.txt
[==================================================] 150B/150B        
Downloading conaninfo.txt
[==================================================] 324B/324B        
bzip2/1.0.6@conan/stable: WARN: Package is corrupted, removing folder: /Users/adam/.conan/data/bzip2/1.0.6/conan/stable/package/534dcc368c999e07e81f146b3466b8f656ef1f55
Downloading conaninfo.txt
[==================================================] 230B/230B        
PROJECT: Installing /Users/adam/CDT-plusplus/conanfile.py
Requirements
    TBB/2018_U5@conan/stable from 'conan-center' - Cache
    boost/1.68.0@conan/stable from 'conan-center' - Cache
    bzip2/1.0.6@conan/stable from 'conan-center' - Cache
    catch2/2.4.0@bincrafters/stable from 'conan-center' - Cache
    date/2.4@bincrafters/stable from 'bincrafters' - Cache
    docopt/0.6.2@conan/stable from 'conan-center' - Cache
    eigen/3.3.5@conan/stable from 'conan-center' - Cache
    gsl_microsoft/1.0.0@bincrafters/stable from 'bincrafters' - Cache
    zlib/1.2.11@conan/stable from 'conan-center' - Cache
Packages
    TBB/2018_U5@conan/stable:03db91a62823ebc2b1df6e5cf549c2f674116656 - Cache
    boost/1.68.0@conan/stable:411d816e9b8d6cb0bb1ef6e5be8b2a94b8b17c04 - Build
    bzip2/1.0.6@conan/stable:534dcc368c999e07e81f146b3466b8f656ef1f55 - Build
    catch2/2.4.0@bincrafters/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Download
    date/2.4@bincrafters/stable:cce31ad1c9344304d9adb841bfd3adef175a5b20 - Build
    docopt/0.6.2@conan/stable:f8bda7f0751e4bc3beaa6c3b2eb02d455291c8a2 - Build
    eigen/3.3.5@conan/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Download
    gsl_microsoft/1.0.0@bincrafters/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Download
    zlib/1.2.11@conan/stable:bad7dd1e4b5daf2b9ae8e3ca2e4397d55b8d3583 - Build
Build requirements
    cmake_installer/3.11.3@conan/stable from 'conan-center' - Cache
Build requirements packages
    cmake_installer/3.11.3@conan/stable:743cf0321be3152777da4d05247a66d1552e70a2 - Download

TBB/2018_U5@conan/stable: Already installed!
bzip2/1.0.6@conan/stable: Building your package in /Users/adam/.conan/data/bzip2/1.0.6/conan/stable/build/534dcc368c999e07e81f146b3466b8f656ef1f55
bzip2/1.0.6@conan/stable: Copying sources to build folder
bzip2/1.0.6@conan/stable: Generator cmake created conanbuildinfo.cmake
bzip2/1.0.6@conan/stable: Calling build()
sh: cmake: command not found
bzip2/1.0.6@conan/stable: 
bzip2/1.0.6@conan/stable: ERROR: Package '534dcc368c999e07e81f146b3466b8f656ef1f55' build failed
bzip2/1.0.6@conan/stable: WARN: Build folder /Users/adam/.conan/data/bzip2/1.0.6/conan/stable/build/534dcc368c999e07e81f146b3466b8f656ef1f55
ERROR: bzip2/1.0.6@conan/stable: Error in build() method, line 50
	cmake.configure(build_dir=".", source_dir="..")
	ConanException: Error 32512 while executing cd '.' && cmake -G "Ninja" -DCMAKE_BUILD_TYPE="Release" -DCONAN_EXPORTED="1" -DCONAN_COMPILER="apple-clang" -DCONAN_COMPILER_VERSION="10.0" -DCONAN_CXX_FLAGS="-m64" -DCONAN_SHARED_LINKER_FLAGS="-m64" -DCONAN_C_FLAGS="-m64" -DBUILD_SHARED_LIBS="OFF" -DCMAKE_INSTALL_PREFIX="/Users/adam/.conan/data/bzip2/1.0.6/conan/stable/package/534dcc368c999e07e81f146b3466b8f656ef1f55" -DCONAN_CMAKE_POSITION_INDEPENDENT_CODE="ON" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -DFPIC="ON" -Wno-dev '..'
ERROR: conanbuildinfo.txt file not found in /Users/adam/CDT-plusplus/build
It is required for this command
You can generate it using 'conan install'

**Comment by memsharded** [comment]
It seems related to cmake not being found in the path:

> sh: cmake: command not found

Which is weird, because the cmake build_requires is there. Might be a bug in conan, not the bzip2 package.

**Comment by lasote** [comment]
Could you paste here the applied profile? I can't find it.

**Comment by acgetchell** [comment]
```
┌─[adam][hapkido][±][feature/refactor-simplicial-manifold ✓][~/CDT-plusplus]
└─▪ conan profile show cdt
Configuration for profile cdt:

[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=10.0
compiler.libcxx=libc++
build_type=Release
[options]
[build_requires]
[env]
CONAN_CMAKE_GENERATOR=Ninja
```

**Comment by acgetchell** [comment]
@memsharded Should I be setting `[build_requires]` in the profile also?

I hadn't before, but ...

**Comment by acgetchell** [comment]
Ah, interesting. If I `brew install cmake` then it works.

**Comment by SSE4** [comment]
This issue was moved to conan-community/community#65
